# Generated by Django 4.0.2 on 2022-04-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarOnRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('Round', models.IntegerField(default=0)),
                ('Level', models.IntegerField(default=0)),
                ('Star', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Roud1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='Roud2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='Roud3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totalEat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='totalStar',
            field=models.IntegerField(default=0),
        ),
    ]
