# Generated by Django 4.0.2 on 2022-04-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_staronround_user_roud1_user_roud2_user_roud3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundAndLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(default=0)),
                ('Round', models.IntegerField(default=0)),
                ('Level', models.IntegerField(default=0)),
                ('Img_snake', models.ImageField(upload_to=None)),
            ],
        ),
    ]
