# Generated by Django 4.0.2 on 2022-04-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_roundandlevel_img_snake_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundandlevel',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
