# Generated by Django 4.0.2 on 2022-04-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_roundandlevel_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundandlevel',
            old_name='Img_snake',
            new_name='ImgSnake',
        ),
        migrations.RenameField(
            model_name='roundandlevel',
            old_name='star',
            new_name='Star',
        ),
        migrations.AddField(
            model_name='roundandlevel',
            name='Background',
            field=models.CharField(default='', max_length=255),
        ),
    ]
