# Generated by Django 4.0.2 on 2022-04-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_img_snake_roundandlevel_imgsnake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundandlevel',
            name='icon',
            field=models.CharField(default='', max_length=255),
        ),
    ]
