# Generated by Django 4.0.2 on 2022-05-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='src_img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
