# Generated by Django 4.0.2 on 2022-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_store_desc_store_price_store_src_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundandlevel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
